import streamlit as st
import pandas as pd
import numpy as np
import joblib

st.set_page_config(page_title="Insurance Premium Estimator", layout="centered")

# --- LOAD MODEL ---
@st.cache_resource
def load_model():
    return joblib.load('interaction_model.pkl')

model = load_model()

# --- HEADER ---
st.title("🛡️ Medical Insurance Cost Estimator")
st.markdown("""
Predict your annual insurance premium based on demographic and lifestyle factors. 
This tool uses a **Multiple Linear Regression** model with **Interaction Effects** to provide high-precision estimates.
""")

st.divider()

# --- INPUT SECTION ---
col1, col2 = st.columns(2)

with col1:
    age = st.slider("Age", 18, 100, 30)
    bmi = st.number_input("BMI (Body Mass Index)", 10.0, 60.0, 25.0)
    children = st.selectbox("Number of Children", [0, 1, 2, 3, 4, 5])

with col2:
    smoker = st.radio("Do you smoke?", ["No", "Yes"])
    sex = st.selectbox("Sex", ["Female", "Male"])
    region = st.selectbox("Region", ["Northeast", "Northwest", "Southeast", "Southwest"])

# --- PREPROCESSING ---
smoker_yes = 1 if smoker == "Yes" else 0
sex_male = 1 if sex == "Male" else 0
reg_nw = 1 if region == "Northwest" else 0
reg_se = 1 if region == "Southeast" else 0
reg_sw = 1 if region == "Southwest" else 0

bmi_x_smoker = bmi * smoker_yes

features = np.array([[age, bmi, children, sex_male, smoker_yes, reg_nw, reg_se, reg_sw, bmi_x_smoker]])

st.divider()

# --- PREDICTION ---
if st.button("Calculate Estimated Premium", type="primary"):
    prediction = model.predict(features)[0]
    
    with st.container(border=True):
        st.subheader("Your Estimated Annual Premium")
        st.metric(label="Estimated Cost", value=f"${prediction:,.2f}")
    
    if smoker == "Yes" and bmi >= 30:
        st.warning("⚠️ **High Risk Detected:** The combination of smoking and a BMI over 30 significantly increases costs due to compounding interaction effects.")
    elif smoker == "Yes":
        st.info("ℹ️ Smoking is the primary driver for your current estimate.")
    
    st.write("### How this was calculated")
    st.caption("This estimate is generated by a regression model trained on the Medical Cost Personal Dataset. It accounts for your base factors and the multiplicative interaction between BMI and lifestyle choices.")